name: Deploy Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-2' }}
  STACK_NAME: ${{ vars.STACK_NAME || 'MotionBackendStack' }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: CDK Bootstrap (idempotent)
        run: npx cdk bootstrap

      - name: Deploy CDK Stack
        run: npx cdk deploy --require-approval never
        env:
          JWT_SECRET: ${{ env.JWT_SECRET }}
          STACK_NAME: ${{ env.STACK_NAME }}
          AWS_REGION: ${{ env.AWS_REGION }}

